### ISSUE TITLE
video generation ipynb demo 

### ISSUE THREAD

**Issue by peymanrah** [XiaohangZhan/conditional-motion-propagation#1]
Thanks for the great contribution. I was wondering if you are able to provide the demo code for the video generation as it was shown in the youtube video. Preferably, the code generates a .gif output, given the arrows/anchors. 

Thanks,

**Comment by XiaohangZhan** [comment]
Hi,
I'm busy with CVPR deadline and cannot tidy up my code for now. I'm sorry for that. You can easily write your own script using the generated flow and a warping layer that can be found  [here](https://github.com/XiaohangZhan/conditional-motion-propagation/blob/c11a2cc4f86aec4800278ce80dff0536d4bd4ff2/models/modules/warp.py#L28).
Note that such naive warping would not yield satisfactory results if the background is too complicated. There will also be some artifacts. You may want to develop the GAN based warping to create more realistic results.
