### ISSUE TITLE
Awesome work

### ISSUE THREAD

**Issue by Zhongdao** [XiaohangZhan/conditional-motion-propagation#2]
I do not have any questions, just want to say this work is aaaaaaaawesome.
It deserves more attention from the self-supervised learning community.
I believe the conditional motion propagation pretext task will play an important role in the future, serving as one crucial component of a multi-task self-supervised learning framework.

**Comment by XiaohangZhan** [comment]
Thank you for your attention, we are constructing a self-supervised learning toolbox under open-mmlab, which will include plenty of representative works, also including CMP, and our new work in CVPR 2020. Please stay tuned!
