### ISSUE TITLE
How did you get the initial guidance here? 

### ISSUE THREAD

**Issue by SiminKou** [XiaohangZhan/conditional-motion-propagation#4]
The article says that the guidance is sampled from the target flow, but what is the basis of the "sparse motion+mask" we input at the beginning? At this time, the static image does not have a corresponding optical flow diagram.

**Comment by XiaohangZhan** [comment]
In training time, we have the target optic flow. It serves as the supervision, also as the basis of the "sparse motion+mask". In testing time, users give the "sparse motion+mask".

**Comment by SiminKou** [comment]
Thank you for your answer. I think this work is wonderful and it gave me a lot of inspiration!
